# Generated by Django 3.2.8 on 2021-10-20 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AuthAppEmpleados', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='capacitacion',
            name='hora',
            field=models.TimeField(default='18:00', verbose_name='hora'),
        ),
        migrations.AlterField(
            model_name='capacitacion',
            name='fecha',
            field=models.DateField(verbose_name='fecha'),
        ),
    ]
