# Generated by Django 3.2.8 on 2021-10-16 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AuthAppEmpleados', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='areacapacitacion',
            name='area',
            field=models.CharField(max_length=55, verbose_name='area'),
        ),
    ]
