# Generated by Django 3.2.8 on 2021-10-16 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AuthAppEmpleados', '0002_alter_areacapacitacion_area'),
    ]

    operations = [
        migrations.AlterField(
            model_name='areacapacitacion',
            name='descripcion',
            field=models.CharField(max_length=120, verbose_name='descripcion'),
        ),
    ]
