# Generated by Django 3.2.8 on 2021-10-16 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AuthAppEmpleados', '0003_alter_areacapacitacion_descripcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='capacitacion',
            name='curso',
            field=models.CharField(max_length=50, verbose_name='curso'),
        ),
    ]
