# Generated by Django 3.2.8 on 2021-10-16 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AuthAppEmpleados', '0004_alter_capacitacion_curso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='capacitacion',
            name='curso',
            field=models.CharField(max_length=60, verbose_name='curso'),
        ),
    ]
